{
 "title": "Gatling Performance",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aggregation",
    "query": "percentiles95, max, mean, min, percentiles50, percentiles75, percentiles99"
   },
   { "name": "test_type", "label": "Test Type", "query": "show measurements" },
   {
    "name": "test",
    "label": "Test",
    "query": "SHOW TAG VALUES FROM /.*/ WITH KEY = \"simulation\""
   },
   {
    "name": "users",
    "label": "Users",
    "query": "SHOW TAG VALUES FROM /.*/ WITH KEY = \"user_count\""
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "SHOW TAG VALUES FROM /.*/ WITH KEY = \"env\""
   },
   {
    "name": "grouping",
    "label": "Grouping",
    "query": "1s,5s,10s,30s,1m,5m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "low_limit", "label": "Yellow Threshold", "query": "250" },
   { "name": "high_limit", "label": "Red Threshold", "query": "700" },
   { "name": "db_name", "query": "gatling" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "total_req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) FROM  \"$test_type\"  WHERE  \"request_name\"= 'allRequests' AND \"simulation\"= '$test' AND \"status\" = 'all'  AND \"user_count\" = '$users' AND \"env\"='$env' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "total_req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) FROM  \"$test_type\"  WHERE  \"request_name\"= 'allRequests' AND \"simulation\"= '$test' AND \"status\" = 'ko'  AND \"user_count\" = '$users' AND \"env\"='$env' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "total_req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(count) FROM  \"$test_type\"  WHERE  \"request_name\"= 'allRequests' AND \"simulation\"= '$test' AND \"status\" = 'all'  AND \"user_count\" = '$users' AND \"env\"='$env' AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min, ms",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "total_req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(min) FROM  \"$test_type\"  WHERE  \"request_name\"= 'allRequests' AND \"simulation\"= '$test' AND \"status\" = 'ok'  AND \"user_count\" = '$users' AND \"env\"='$env' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Median, ms",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "total_req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentiles50) FROM  \"$test_type\"  WHERE  \"request_name\"= 'allRequests' AND \"simulation\"= '$test' AND \"status\" = 'ok'  AND \"user_count\" = '$users' AND \"env\"='$env' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$aggregation, ms",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "total_req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max($aggregation) FROM  \"$test_type\"  WHERE  \"request_name\"= 'allRequests' AND \"simulation\"= '$test' AND \"status\" = 'ok'  AND \"user_count\" = '$users' AND \"env\"='$env' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times Over Time ($grouping aggregation)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"$aggregation\") FROM \"$test_type\" WHERE env='$env' AND simulation='$test' AND user_count='$users' and status='ok' AND request_name != 'allRequests' AND $timeFilter GROUP BY time($grouping), request_name fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "active users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"active\") FROM \"users\" WHERE  env='$env' AND simulation='$test' AND user_count='$users' AND $timeFilter GROUP BY time($grouping) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILED.$tag_request_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"$aggregation\") FROM \"$test_type\" WHERE env='$env' AND simulation='$test' AND user_count='$users' and status='ko' AND request_name != 'allRequests' AND $timeFilter GROUP BY time($grouping), request_name fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput ($grouping aggregation)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "alias": "active users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"active\") FROM \"users\" WHERE test_type='$test_type' AND simulation='$test' AND user_count='$users' AND env='$env' AND $timeFilter GROUP BY time($grouping) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"count\") as \"max_1s\" FROM \"$test_type\" WHERE simulation='$test'  AND status = 'ok' AND user_count='$users' AND env='$env' AND  \"request_name\" = 'allRequests' AND $timeFilter GROUP BY time($grouping)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") as \"avg_1s\" FROM \"$test_type\" WHERE simulation='$test'  AND status = 'ok' AND user_count='$users' AND env='$env' AND  \"request_name\" = 'allRequests' AND $timeFilter GROUP BY time($grouping)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"count\") as \"ko_tps\" FROM \"$test_type\" WHERE simulation='$test'  AND status = 'ko' AND user_count='$users' AND env='$env' AND  \"request_name\" = 'allRequests' AND $timeFilter GROUP BY time($grouping)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$aggregation response time distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "t < $low_limit ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) FROM \"$test_type\" WHERE request_name='allRequests'  AND simulation='$test' AND user_count='$users' AND status='ok' AND \"$aggregation\"<=$low_limit AND env ='$env' AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$low_limit  < t < $high_limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) FROM \"$test_type\" WHERE request_name='allRequests'  AND simulation='$test' AND user_count='$users' AND status='ok' AND \"$aggregation\">$low_limit AND \"$aggregation\"<$high_limit  AND env ='$env' AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "t > $high_limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) FROM \"$test_type\" WHERE request_name='allRequests'  AND simulation='$test' AND user_count='$users' AND status='ok' AND \"$aggregation\">=$high_limit  AND env ='$env' AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) FROM \"$test_type\" WHERE request_name='allRequests'  AND simulation='$test' AND user_count='$users' AND status='ko' AND env ='$env' AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_request_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count FROM  \"$test_type\"  WHERE  \"request_name\"!= 'allRequests' AND \"simulation\"= '$test' AND \"status\" = 'ok'  AND \"user_count\" = '$users' AND \"env\"='$env' AND $timeFilter GROUP BY request_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Summary Table",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "content": "<script type=\"text/javascript\" language=\"javascript\" src=\"//cdn.jsdelivr.net/gh/carrier-io/carrier-io/grafana_libs/grafana_wrapper.js\" />\n<script type=\"text/javascript\" language=\"javascript\" src=\"//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js \"/>\n<script>\nfunction generateQuery(wrapper){\n    function appendValues(name,arr){\n        return (arr.length) ? (name + '=~ /^(' + arr.join('|') + ')$/ AND ') : '';\n    }\n\n    var AND  = ' AND ';\n    var WHERE = ' WHERE ';\n    var GROUP_BY = ' GROUP BY request_name; ';\n    var query;\n    var testTypes = wrapper.getVar('test_type', onAllEmpty=false).toString();\n    var environments = appendValues('env', wrapper.getVar('env'));\n    var userCounts = appendValues('user_count', wrapper.getVar('users'));\n\n    var simulation = ' simulation=\\'' +  wrapper.getVar('test')[0] + '\\'';\n    var timeFilter = wrapper.getTime()['filter'];\n    var from_block =  testTypes + WHERE + simulation + AND + userCounts + environments;\n\n    query = 'SELECT SUM(count) AS \"total\" FROM ' + from_block + 'status= \\'all\\'' + AND +  timeFilter + GROUP_BY;\n    query += 'SELECT SUM(count) AS \"ok\" FROM ' + from_block +  'status= \\'ok\\'' + AND + timeFilter + GROUP_BY;\n\n    duplicate_part =  from_block +  'status= \\'all\\'' + AND +  timeFilter + GROUP_BY;\n    query += 'SELECT MEAN(avrg_rps) AS \"rps\" FROM (SELECT MEAN(count) AS \"avrg_rps\" FROM ' + from_block +' status= \\'ok\\' AND ' + timeFilter+ ' GROUP BY time(1s)) GROUP BY request_name;'\n\n    query += 'SELECT MIN(min) AS \"min\", MEAN(mean) AS \"average\", MAX(max) AS \"max\"  FROM ' + duplicate_part;\n    query += 'SELECT STDDEV(mean)        AS \"stddev\" FROM ' + duplicate_part;\n    query += 'SELECT MEDIAN(mean)        AS \"median\" FROM ' + duplicate_part;\n    query += 'SELECT PERCENTILE(mean,75) AS \"perc75\" FROM ' + duplicate_part;\n    query += 'SELECT PERCENTILE(mean,95) AS \"perc95\" FROM ' + duplicate_part;\n    query += 'SELECT PERCENTILE(mean,99) AS \"perc99\" FROM ' + duplicate_part;\n\n    return query;\n};\n\nfunction formatDataset(data){\n    rows = {};\n    results = data.results;\n    results.forEach(function(result, i) {\n        series = result.series;\n        series.forEach(function(serie, s) {\n            var request_name = serie.tags.request_name\n            var keys = serie.columns.slice(1);\n            var values = serie.values[0].slice(1);\n            var row = (request_name in rows) ? rows[request_name] : {};\n            values.forEach( function(value, v) {\n                row[keys[v]] = value!=null ? value : 0;\n            });\n            rows[request_name] = row;\n        });\n    });\n    return rows\n}\n\nfunction appendSTRow(row){\n    $('#summary-table').DataTable().row.add(row).draw()\n}\n\nfunction retrieveData(db_name, query){\n    $.get(\"/grafana/api/datasources/proxy/4/query\", { q: query, db: \"$db_name\", epoch: EPOCH},\n        function(data, status){\n            if(status == 'success'){\n                var series = data.results[0].series\n                if(typeof series == 'undefined'){\n                    showErrMessage(\"No datapoints in selected time range. Try to change filter parameters.\")\n                }else{\n                    removeSpinner()\n                    var rows = formatDataset(data)\n                    generateSummaryDataTable()\n                    for (request_name in rows){\n                        request = rows[request_name]\n                        var total =  request['total']\n                        var ok = request['ok']\n                        var ko =  total > ok  ? total - ok : 0\n\n                        var ko_perc = ko > 0 ? parseFloat((ko/total) * 100).toFixed(ROUND_FLOAT_FACTOR) : 0.00\n                        var rps = request['rps'] ==null ? 0.0 : parseFloat(request['rps']).toFixed(3)\n                        var min = request['min'] ==null ? 0.0 : parseFloat(request['min']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        var median = request['median'] ==null ? 0.0 : parseFloat(request['median']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        var perc75 = request['perc75'] ==null ? 0.0 : parseFloat(request['perc75']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        var perc95 = request['perc95'] ==null ? 0.0 : parseFloat(request['perc95']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        var perc99 = request['perc99'] ==null ? 0.0 : parseFloat(request['perc99']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        var max = request['max'] ==null ? 0.0 : parseFloat(request['max']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        var average = request['average'] ==null ? 0.0 : parseFloat(request['average']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        var stddev = request['stddev'] ==null ? 0.0 : parseFloat(request['stddev']/1000).toFixed(ROUND_FLOAT_FACTOR)\n                        row = [request_name, total, ok, ko, ko_perc, rps, min, median, perc75, perc95, perc99, max, average, stddev]\n\n                        appendSTRow(row)\n                    }\n                }\n            }else{\n                showErrMessage(\"Error occured during quering data. Check your datasource settings.\")\n            }\n        });\n}\n\nfunction emptySummaryTable(){\n    $(\"#summary\").empty();\n}\n\nfunction addSpinner(){\n    if ($('div.spinner').length == 0){\n        var spinner = $('<div>')\n        spinner.attr(\"class\",\"spinner\");\n        spinner.html(\"<div  style=\\\"text-align: center;\\\"> <i class=\\\"fa fa-spinner fa-spin\\\" style=\\\" font-size: xx-large;\\\"></i> </div>\")\n        $(\"#summary\").append(spinner)\n    }\n}\nfunction removeSpinner(){\n    $('#summary div.spinner').remove()\n}\n\nfunction initSummaryDataTable(table){\n    table.DataTable({\n        \"empty\": true,\n        \"iDisplayLength\": 10,\n        \"lengthMenu\": [[5, 10, 20, 40, -1], [5, 10, 20, 40, \"All\"]],\n        \"order\": [[ 0, \"asc\" ]],\n        \"pagingType\": \"full_numbers\",\n        \"responsive\": true,\n        \"rowCallback\": function(row, data, index){\n            // errors\n            if(data[4] > 0. && data[4] <= ERROR_PERC_TRESHOLD){\n                $(row).find('td:eq(3)').css('color', 'orange');\n                $(row).find('td:eq(4)').css('color', 'orange');\n            }else if(data[4] > ERROR_PERC_TRESHOLD){\n                $(row).find('td:eq(3)').css('color', 'red');\n                $(row).find('td:eq(4)').css('color', 'red');\n            }\n            // response times\n            for (var i = 6; i <= 13; i++){\n\n                if(data[i] < LOWER_RT_TRESHOLD){\n                    $(row).find('td:eq('+i+')').css('color', 'green');\n                    $(row).find('td:eq('+i+')').css('color', 'green');\n                }else if(data[i] > HIGHER_RT_TRESHOLD){\n\n                    $(row).find('td:eq('+i+')').css('color', 'red');\n                    $(row).find('td:eq('+i+')').css('color', 'red');\n                }else{\n                    $(row).find('td:eq('+i+')').css('color', 'orange');\n                    $(row).find('td:eq('+i+')').css('color', 'orange');\n                }\n            }\n        }\n    });\n}\n\nfunction generateSummaryDataTable(){\n    emptySummaryTable();\n    var table = $('<table>');\n    table.attr(\"id\",\"summary-table\");\n    table.append(generateSTHead());\n    table.append(generateSTBody());\n    $('#summary').append(table);\n    initSummaryDataTable(table);\n    addSTSelectionFeature();\n}\n\nfunction generateSTHead(){\n    var cellNames = [\"Requests\",\"Total\",\"OK\",\"KO\",\"% KO\",\"Req/s\",\"Min\",\"50th pct\",\"75th pct\",\"95th pct\",\"99th pct\",\"Max\",\"Average\",\"Std Dev\"];\n    tHead = $('<thead>');\n    tHead.attr(\"id\",\"summary-table-head\");\n    tRow = $('<tr>');\n    for (var i = 0; i < cellNames.length; i++){\n        tHeadCell = $('<th>');\n        tHeadCell.text(cellNames[i])\n        tRow.append(tHeadCell);\n    }\n    tHead.append(tRow);\n\n    return tHead;\n}\nfunction generateSTBody(){\n    var tBody = $('<tbody>');\n    tBody.attr(\"id\",\"summary-table-body\");\n\n    return tBody;\n}\n\nfunction addSTSelectionFeature(){\n    var table = $('#summary-table').DataTable();\n    $('#summary-table tbody').on( 'click', 'tr', function () {\n        if ($(this).hasClass('selected')) {\n            $(this).removeClass('selected');\n        }\n        else {\n            table.$('tr.selected').removeClass('selected');\n            $(this).addClass('selected');\n        }\n    } );\n\n    $('#button').click( function () {\n        table.row('.selected').remove().draw( false );\n    } );\n}\n\nfunction showErrMessage(errMessage){\n    removeSpinner();\n    $(\"#summary\").empty();\n    message = $('<span>');\n    message.attr(\"id\",\"summary-table-message\");\n    message.text(errMessage);\n    $(\"#summary\").append(message);\n}\n\nfunction waitForSTGWrapper(){\n    addSpinner();\n    try{\n        var wrapper = new GWrapper(\"API_Summary_Table\");\n        checkSTIsLoaded(wrapper)\n    }catch(err){\n        setTimeout(function() { waitForSTGWrapper()}, 500);\n    }\n}\n\nfunction checkSTIsLoaded(wrapper){\n    if($.fn.DataTable){\n        query = generateQuery(wrapper);\n        db_name = wrapper.getVar('db_name');\n        retrieveData(db_name, query);\n    }else{\n        setTimeout(function() { checkSTIsLoaded()}, 500);\n    }\n}\n\nEPOCH = \"ms\";\nTABLE_TIME_EPOCH = 's'; //s for seconds, any other value for milliseconds\n\nLOWER_RT_TRESHOLD = parseFloat(\"$low_limit\")/1000.0\nHIGHER_RT_TRESHOLD = parseFloat(\"$high_limit\")/1000.0\nERROR_PERC_TRESHOLD = 1.0;\nROUND_FLOAT_FACTOR = 3;\n\nwindow.onload = waitForSTGWrapper();\nangular.element('grafana-app').injector().get('$rootScope').$on('refresh',function(){waitForSTGWrapper()});\n</script>\n\n\n<style type=\"text/css\">\n    #summary-table-body>tr.selected{ background: #292929; font-weight: 600;} #summary-table-body>tr:hover{ background: #292929;} #summary-table td{text-align:center} #summary-table-body > tr>:nth-child(1) {text-align:left}\n    #summary-table_filter,.dataTables_length{display:inline-block}.dataTables_length{padding-bottom:20px;padding-right:23px}input[type=search]{border-radius:5px}select[name=summary-table_length]{height:23px;width:65px;border-radius:5px}.paging_full_numbers>a,.paging_full_numbers>span>a{padding-right:10px}#summary-table-message{display:table;margin-left:auto;margin-right:auto}#summary-table{width:100%!important}th{text-align:center}\n</style>\n<div id = \"summary\"></div>"
  }
 ]
}