apiVersion: v1
kind: Service
metadata:
  annotations:
    carrier: auth
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.carrier-auth.rule: PathPrefix(`/forward-auth`)
    traefik.http.services.carrier-auth.loadbalancer.server.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: auth
status:
  loadBalancer: {}
