apiVersion: v1
kind: Service
metadata:
  annotations:
    carrier: galloper
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "true"
    traefik.http.middlewares.galloper-auth.forwardauth.address: http://carrier-auth/forward-auth/auth?target=json&scope=galloper
    traefik.http.routers.galloper.middlewares: galloper-auth@docker
    traefik.http.routers.galloper.rule: PathPrefix(`/`)
    traefik.http.services.galloper.loadbalancer.server.port: "5000"
  creationTimestamp: null
  labels:
    io.kompose.service: galloper
  name: galloper
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: galloper
status:
  loadBalancer: {}
