apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: interceptor
  name: interceptor
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: interceptor
    spec:
      containers:
      - env:
        - name: CPU_CORES
        - name: CPU_QUOTA
        - name: RAM_QUOTA
        - name: REDIS_HOST
          value: carrier-redis
        - name: REDIS_PASSWORD
        image: getcarrier/interceptor:latest
        name: carrier-interceptor
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: interceptor-claim0
      restartPolicy: Always
      volumes:
      - name: interceptor-claim0
        persistentVolumeClaim:
          claimName: interceptor-claim0
status: {}
