{
 "title": "jmeter Load Test",
 "description": "This dashboard shows live load test metrics provided by jMeter.",
 "tags": [ "performance_test" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "projectID",
    "label": "Project ID",
    "query": "SHOW TAG VALUES FROM /.*/ WITH KEY = \"projectName\""
   },
   {
    "name": "envType",
    "label": "Environment Type",
    "query": "SHOW TAG VALUES FROM /.*/ WITH KEY = \"envType\"  WHERE  \"projectName\" =~ /^$projectID$/"
   },
   {
    "name": "testName",
    "label": "Test Type",
    "query": "SHOW TAG VALUES FROM /.*/ WITH KEY = \"testType\"  WHERE  \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/"
   },
   {
    "name": "request",
    "label": "Requests",
    "query": "SHOW TAG VALUES FROM /.*/ WITH KEY = \"requestName\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/"
   },
   {
    "name": "responseCode",
    "label": "responseCode",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY = \"responseCode\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/"
   },
   { "name": "aggregation", "label": "Aggregation Interval", "query": "500ms,1s,2s,3s,5s,10s,15s,30s" },
   {
    "name": "lg",
    "query": "show tag values from requestsRaw with key=loadGenerator"
   },
   { "name": "grouping", "query": "1s,10s,30s,1m,10m,30m,1h" },
   { "name": "low_limit", "label": "low_limit", "query": "2000" },
   { "name": "high_limit", "label": "high_limit", "query": "3000" }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total request count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT count(\"responseTime\") FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total failed requests count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "fields": [
      { "func": "last", "name": "err" }
     ],
     "measurement": "jmeter_samples",
     "query": "SELECT sum(\"errorCount\") FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "application",
       "operator": "=~",
       "value": "/^[^#]+#$test_name#$test_run_id$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT mean(\"throughput\") FROM (SELECT count(responseTime) AS \"throughput\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY time(1s))",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT max(\"throughput\") FROM (SELECT count(responseTime) AS \"throughput\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY time(1s))",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"responseTime\") FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Median",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"responseTime\") FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "95th percentile",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"responseTime\",95) FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times Over Time ($aggregation aggregation)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms", "label": "Response time" }
   ],
   "targets": [
    {
     "alias": "$tag_requestName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT mean(\"responseTime\") FROM \"requestsRaw\" WHERE \"errorCount\" = 0 AND \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND \"requestName\" =~ /^$request$/  AND loadGenerator =~ /^$lg$/ AND $timeFilter GROUP BY time($aggregation), \"requestName\" fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "FAILED $tag_requestName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT mean(\"responseTime\") FROM \"requestsRaw\" WHERE \"errorCount\" = 1 AND \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND \"requestName\" =~ /^$request$/  AND loadGenerator =~ /^$lg$/ AND $timeFilter GROUP BY time($aggregation), \"requestName\" fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "active users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(sum) from (SELECT sum(\"maxActiveThreads\")/10 FROM \"virtualUsers\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND loadGenerator =~ /^$lg$/ AND $timeFilter GROUP BY time(10s)) GROUP BY time($aggregation)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput ($aggregation aggregation)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "Requests per second" }
   ],
   "targets": [
    {
     "alias": "active users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"maxActiveThreads\")/10 FROM \"virtualUsers\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND loadGenerator =~ /^$lg$/ AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"maxCount\") FROM (SELECT count(responseTime) AS \"maxCount\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"status\" = 'OK' AND \"testType\" =~ /^$testName$/ AND loadGenerator =~ /^$lg$/ AND $timeFilter  GROUP BY time(1s))GROUP BY time($aggregation)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"meanCount\") FROM (SELECT count(responseTime) AS \"meanCount\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"status\" = 'OK'  AND \"testType\" =~ /^$testName$/ AND loadGenerator =~ /^$lg$/  AND $timeFilter  GROUP BY time(1s))GROUP BY time($aggregation)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "failed requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "virtualUsers",
     "query": "SELECT max(\"maxCount\") FROM (SELECT count(responseTime) AS \"maxCount\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"status\" = 'KO' AND \"testType\" =~ /^$testName$/  AND loadGenerator =~ /^$lg$/ AND $timeFilter  GROUP BY time(1s))GROUP BY time($aggregation)",
     "select": [
      [
       { "params": [ "maxActiveThreads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time distribution ($aggregation aggregation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Request count" }
   ],
   "targets": [
    {
     "alias": "t < $low_limit ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"responseTime\") as \"CountA\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND \"status\" = 'OK' AND \"responseTime\"<=$low_limit AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$low_limit  < t < $high_limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"responseTime\") as \"CountA\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND \"status\" = 'OK' AND \"responseTime\">$low_limit AND \"responseTime\"<$high_limit  AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "t > $high_limit ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"responseTime\") as \"CountA\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND \"status\" = 'OK' AND \"responseTime\">$high_limit AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"responseTime\") as \"CountA\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND \"status\" = 'KO' AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Throughput Over Time, bytes/$aggregation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Bytes recieved per $aggregation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"responseBytes\") FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY time($aggregation)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Bytes sent per $aggregation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"requestBytes\") FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY time($aggregation)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Summary table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Aggregate Report",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "alias": "$tag_requestName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT count(responseTime) as Count, mean(responseTime)/1000 as Average, median(responseTime)/1000 as Median, percentile(responseTime, 90)/1000 as \"90% Line\",percentile(responseTime, 95)/1000 as \"95% Line\",percentile(responseTime, 99)/1000 as \"99% Line\", min(responseTime)/1000 as Min, max(responseTime)/1000 as Max, (sum(errorCount)/count(responseTime))*100 as \"Error Rate\", stddev(\"responseTime\") as \"Standard Deviation\",last(tpsRate) as \"Throughput\",last(networkRate) as \"Network Throughput\" FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP(S) Connect Times Per $aggregation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_requestName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"connectTime\") FROM \"requestsRaw\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY time($aggregation), \"requestName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Codes Over Time with $aggregation granulation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_responseCode",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT count(\"responseTime\") FROM \"requestsRaw\" WHERE projectName =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/  AND \"testType\" =~ /^$testName$/  AND \"responseCode\" =~ /^$responseCode$/  AND $timeFilter GROUP BY time($aggregation), \"responseCode\" fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"errorMessage\") AS \"Failed asertion(s)\",  last(\"errorMessage\") AS \"Last Message\" FROM  \"errorMessage\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY  \"requestName\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed errors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "All errors",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT errorMessage AS \"All Messages\" FROM \"errorMessage\" WHERE \"projectName\" =~ /^$projectID$/ AND \"envType\" =~ /^$envType$/ AND \"testType\" =~ /^$testName$/ AND $timeFilter GROUP BY  \"requestName\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}