{
 "title": "UI Performance",
 "tags": [ "ui" ],
 "time": { "from": "2018-12-05T23:52:25.897Z", "to": "2018-12-05T23:56:02.234Z" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "Scenario",
    "query": "SHOW TAG VALUES WITH KEY = \"scenario\""
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "SHOW TAG VALUES FROM \"uiperf\" WITH KEY = \"domain\""
   },
   {
    "name": "page_name",
    "label": "Page",
    "query": "SHOW TAG VALUES FROM \"uiperf\" WITH KEY = \"page\" WHERE domain =~ /$domain/ AND scenario =~ /(?i)$scenario/"
   },
   {
    "name": "rps_interval",
    "label": "rps_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "db_name", "query": "perfui" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Pages/Actions count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT SUM(count) FROM \"uiperf\" WHERE \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /(?i)^$scenario$/ AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/(?i)^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Failed Pages count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT SUM(count) FROM \"uiperf\" WHERE \"scenario\" =~ /(?i)^$scenario$/ AND status = 'ko' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/(?i)^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT SUM(count) FROM \"uiperf\" WHERE \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /(?i)^$scenario$/ AND status = 'ko' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/(?i)^$scenario$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Response Transfer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT SUM(count) FROM \"uiperf\" WHERE \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /(?i)^$scenario$/ AND status = 'ko' AND $timeFilter GROUP BY count",
     "select": [
      [
       { "params": [ "transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/(?i)^$scenario$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Browser processing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT  max(\"onload\") +  max(\"tti\")  +  max(\"ttl\")  FROM \"uiperf\" WHERE \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /(?i)^$scenario$/ AND status = 'ok' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "onload" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/(?i)^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Page/Action time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT  max(\"ttl\")  FROM \"uiperf\" WHERE \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /(?i)^$scenario$/ AND status = 'ok' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/(?i)^$scenario$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Page load time summary",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"latency\") FROM \"uiperf\" WHERE scenario=~ /$scenario/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    },
    {
     "alias": "Response transfer",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"transfer\") FROM \"uiperf\" WHERE scenario=~ /$scenario/ AND  \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    },
    {
     "alias": "Time to DOM Interactive",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"tti\") FROM \"uiperf\" WHERE  scenario=~ /$scenario/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "tti" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    },
    {
     "alias": "Time to DOM Load",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"ttl\") FROM \"uiperf\" WHERE scenario=~ /$scenario/ AND  \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "ttl" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    },
    {
     "alias": "Onload event time",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"onload\") FROM \"uiperf\" WHERE scenario=~ /$scenario/ AND  \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "ttl" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    },
    {
     "alias": "Total time",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"total_time\") FROM \"uiperf\" WHERE  scenario=~ /$scenario/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"total_time\") FROM \"uiperf\" WHERE  scenario=~ /$scenario/ AND \"status\" = 'ko' AND \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  { "title": "$page_name Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "page_name" },
  {
   "title": "$page_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"latency\") FROM \"uiperf\" WHERE (\"page\" =~ /^$page_name$/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page_name$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "Transfer",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"transfer\") FROM \"uiperf\" WHERE (\"page\" =~ /^$page_name$/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page_name(Page)$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "Time to DOM Interactive",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"tti\") FROM \"uiperf\" WHERE (\"page\" =~ /^$page_name$/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "tti" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page_name(Page)$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "Time to DOM Load",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"ttl\") FROM \"uiperf\" WHERE (\"page\" =~ /^$page_name$/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "ttl" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page_name(Page)$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "Onload event time",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "select": [
      [
       { "params": [ "onload" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page_name$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "Total time",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"total_time\") FROM \"uiperf\" WHERE (\"page\" =~ /^$page_name$/ AND \"status\" = 'ok' AND \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page_name$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$rps_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uiperf",
     "query": "SELECT max(\"total_time\") FROM \"uiperf\" WHERE \"page\" =~ /^$page_name$/ AND \"status\" = 'ko' AND \"domain\" =~ /^$domain$/ AND \"scenario\" =~ /^$scenario$/ AND $timeFilter GROUP BY time($rps_interval) fill(null)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page_name(Page)$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentiles Summary",
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "content": "<script type=\"text/javascript\" language=\"javascript\" src=\"//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js\" />\n<script type=\"text/javascript\" language=\"javascript\" src='//cdn.jsdelivr.net/gh/carrier-io/perf-ui@master/lib/grafana_wrapper.js'\n/>\n<script type=\"text/javascript\" language=\"javascript\" src='//cdn.jsdelivr.net/gh/carrier-io/perf-ui@master/lib/timing_api_waterfall.js' />\n<script>\n\n    function addSpinner$page_name() {\n        $('#timingApiTable$page_name').empty();\n        if ($('div.$page_name-spinner').length == 0) {\n            var spinner = $('<div>')\n            spinner.attr(\"class\", \"$page_name-spinner\");\n            spinner.html(\"<div  style=\\\"text-align: center;\\\"> <i class=\\\"fa fa-spinner fa-spin\\\" style=\\\" font-size: xx-large;\\\"></i> </div>\")\n            $(\"#timingApiTable$page_name\").append(spinner)\n        }\n    }\n\n    function removeSpinner$page_name() {\n        $('div.$page_name-spinner').remove()\n    }\n\n    function getQuery$page_name(wrapper, percentile, pageName, timing) {\n        criterion = '';\n        if (percentile.indexOf(\"in\") > 0) {\n            criterion = \"MIN(\\\"\" + timing + \"\\\")\";\n        } else if (percentile.indexOf(\"ax\") > 0) {\n            criterion = \"MAX(\\\"\" + timing + \"\\\")\";\n        } else {\n            criterion = \"PERCENTILE(\\\"\" + timing + \"\\\",\" + percentile.replace(\" pct\", \"\") + \")\"\n        }\n        var timeFilter = wrapper.getTime()['filter'];\n        var scenario = wrapper.getVar('scenario')[0];\n\n        return 'select ' + criterion + ' AS \"' + percentile\n            + '\", raw_data_timing, raw_objects_timing from $db_name..\"uiperf\" where scenario= \\''\n            + scenario + '\\' AND status=~ /ok/ AND page=~ /^'\n            + pageName + '/ and '\n            + timeFilter + \"; \";\n    }\n\n    var db_url = \"/grafana/api/datasources/proxy/2/query\";\n    var db_name = \"$db_name\";\n\n    var tabl_data = [\n        { name: \"Min\", total_time: 0, raw_data_timing: \"\", raw_objects_timing: \"\" },\n        { name: \"50 pct\", total_time: 0, raw_data_timing: \"\", raw_objects_timing: \"\" },\n        { name: \"75 pct\", total_time: 0, raw_data_timing: \"\", raw_objects_timing: \"\" },\n        { name: \"90 pct\", total_time: 0, raw_data_timing: \"\", raw_objects_timing: \"\" },\n        { name: \"95 pct\", total_time: 0, raw_data_timing: \"\", raw_objects_timing: \"\" },\n        { name: \"99 pct\", total_time: 0, raw_data_timing: \"\", raw_objects_timing: \"\" },\n        { name: \"Max\", total_time: 0, raw_data_timing: \"\", raw_objects_timing: \"\" }\n    ];\n\n    function generateRow(ind, rowData, pageName) {\n        var tr = $('<tr/>');\n        var dataCell = $('<td/>');\n        var linkEll = $('<a/>')\n        var id = rowData['name'] + '_' + pageName + '_' + ind\n        linkEll.attr(\"id\", id);\n        linkEll.attr(\"href\", '#');\n        linkEll.text(rowData['name']);\n        dataCell.append(linkEll);\n        var script = document.createElement('script');\n        script.type = 'text/javascript';\n        script.text = 'function ShowBig_' + pageName + '_' + ind + '(){showBigPicture(' + rowData['raw_objects_timing'] + ',' + rowData[\"raw_data_timing\"] + ');};\\nvar el = document.getElementById(\"' + id + '\");\\nel.onclick=ShowBig_' + pageName + '_' + ind + ';';\n        dataCell.append(script);\n        tr.append(dataCell);\n        var infoCell = $('<td/>');\n        var textEll = $('<span/>');\n        textEll.text(rowData[\"total_time\"].toString());\n        infoCell.append(textEll);\n        tr.append(infoCell);\n\n        return tr\n    }\n\n    function checkDataTableIsLoaded$page_name(wrapper, tabl_data, pageName, timing) {\n        addSpinner$page_name()\n        var query = \"\"\n        var table = $('<table/>');\n        table.attr(\"width\", \"100%\");\n\n        for (var i = 0; i < tabl_data.length; i++)\n            query += getQuery$page_name(wrapper, tabl_data[i]['name'], pageName, timing);\n\n        $.post(db_url, { q: query, db: db_name, epoch: \"ms\" }).done(function (data, status) {\n            var data = data.results\n            if (!data || !data[0]['series']) {\n                console.log(\"no series\")\n                showTimingTableMessage$page_name('No successful requests in selected time range.')\n            } else {\n                for (var i = 0; i < data.length; i++) {\n                    var rowData = data[i]\n                    var result_json = {\n                        name: rowData['series'][0]['columns'][1],\n                        total_time: rowData['series'][0]['values'][0][1],\n                        raw_data_timing: rowData[\"series\"][0]['values'][0][2],\n                        raw_objects_timing: rowData[\"series\"][0]['values'][0][3]\n                    }\n                    table.append(generateRow(i.toString(), result_json, pageName));\n                }\n                $('#timingApiTable$page_name').empty();\n                $('#timingApiTable$page_name').append(table);\n            }\n        })\n    }\n\n    function showTimingTableMessage$page_name(mess) {\n        removeSpinner$page_name()\n        $('#timingApiTable$page_name').empty();\n        var message = $('<span>');\n        message.attr(\"id\", \"timing-table-message\");\n        message.text(mess)\n        $('#timingApiTable$page_name').append(message);\n    }\n\n    function waitForGWrapper$page_name() {\n        try {\n            var wrapper = new GWrapper('UI_page_details');\n            var pageName = '$page_name'\n            var timeFilter = wrapper.getTime()['filter'];\n            var scenario = wrapper.getVar('scenario')[0];\n            var timing = \"total_time\"\n            var test_q = 'SELECT \"total_time\",\"duration\" FROM \"uiperf\" WHERE \"page\" =~ /^$page_name/ AND '\n                + 'scenario=~ /^' + scenario + '/' + ' AND status=~ /ok/ and ' + timeFilter + ' limit 1';\n\n\n            $.post(db_url, { q: test_q, db: db_name, epoch: \"ms\" }).done(function (data, status) {\n                var data = data.results\n                if (!data[0].series) {\n                    showTimingTableMessage$page_name('No successful requests in selected time range.')\n                } else {\n                    if (data[0].series[0].values[0][2] != null)\n                        timing = \"duration\";\n\n                    checkDataTableIsLoaded$page_name(wrapper, tabl_data, pageName, timing);\n                }\n            })\n        } catch (err) {\n            console.log(\"Errors \" + err)\n            setTimeout(function () { waitForGWrapper$page_name() }, 500);\n        }\n    }\n\n    $(document).ready(function () { waitForGWrapper$page_name(); });\n    angular.element('grafana-app').injector().get('$rootScope').$on('refresh', function () { waitForGWrapper$page_name() })\n\n</script>\n<style>\n    #timing-table-message {\n        display: table;\n        margin-left: auto;\n        margin-right: auto;\n        text-align: center;\n    }\n</style>\n<div id=\"timingApiTable$page_name\"></div>"
  }
 ]
}