apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: influx
  name: influx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influx
    spec:
      containers:
      - env:
        - name: INFLUXDB_DATA_DIR
          value: /var/lib/influxdb/data
        - name: INFLUXDB_DATA_WAL_DIR
          value: /var/lib/influxdb/wal
        - name: INFLUXDB_HTTP_ENABLED
          value: "true"
        - name: INFLUXDB_META_DIR
          value: /var/lib/influxdb/meta
        image: influxdb:1.7
        name: carrier-influx
        ports:
        - containerPort: 2003
        - containerPort: 8086
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb/data
          name: influx-claim0
      restartPolicy: Always
      volumes:
      - name: influx-claim0
        persistentVolumeClaim:
          claimName: influx-claim0
status: {}
