apiVersion: v1
kind: Service
metadata:
  annotations:
    carrier: keycloak
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.keycloak.rule: PathPrefix(`/auth`)
    traefik.http.services.keycloak.loadbalancer.server.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: keycloak
status:
  loadBalancer: {}
