apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: observer-chrome
  name: observer-chrome
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  - name: "9999"
    port: 9999
    targetPort: 9999
  selector:
    io.kompose.service: observer-chrome
status:
  loadBalancer: {}
