apiVersion: v1
kind: Service
metadata:
  annotations:
    carrier: postgres
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
