apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - command:
        - redis-server
        - --requirepass
        - password
        image: redis:5.0.7
        name: carrier-redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
