apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    carrier: vault
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: vault
  name: vault
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vault
    spec:
      containers:
      - args:
        - vault
        - server
        - -config=/vault/config/local.json
        volumeMounts:
        - mountPath: /vault/config/local.json
          name: vault-config
          subPath: local.json
        env:
        - name: VAULT_LOCAL_CONFIG
          valueFrom:
            secretKeyRef:
              key: vault.json
              name: vault-config
        image: vault:latest
        name: carrier-vault
        resources: {}
      restartPolicy: Always
      volumes:
      - name: vault-config
        secret:
          secretName: vault-config
status: {}


